# uncompyle6 version 3.8.1.dev0
# Python bytecode 3.7.0 (3394)
# Decompiled from: Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: UiAdd.py
from MyLib import *
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):

    def setupUi(self, Dialog):
        Dialog.setObjectName('Dialog')
        Dialog.setWindowModality(QtCore.Qt.ApplicationModal)
        Dialog.resize(382, 143)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('.\\res\\02.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        Dialog.setModal(True)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 39, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName('label_2')
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 3, 121, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName('label')
        self.btn_cancel = QtWidgets.QPushButton(Dialog)
        self.btn_cancel.setGeometry(QtCore.QRect(178, 100, 93, 33))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap('.\\res\\06.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_cancel.setIcon(icon1)
        self.btn_cancel.setObjectName('btn_cancel')
        self.btn_save = QtWidgets.QPushButton(Dialog)
        self.btn_save.setGeometry(QtCore.QRect(278, 100, 93, 33))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap('.\\res\\05.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon2)
        self.btn_save.setAutoExclusive(False)
        self.btn_save.setAutoDefault(False)
        self.btn_save.setDefault(True)
        self.btn_save.setObjectName('btn_save')
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 69, 121, 20))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName('label_3')
        self.txt_cat_name = QtWidgets.QLineEdit(Dialog)
        self.txt_cat_name.setGeometry(QtCore.QRect(140, 10, 230, 23))
        self.txt_cat_name.setObjectName('txt_cat_name')
        self.txt_sub_cat_name = QtWidgets.QLineEdit(Dialog)
        self.txt_sub_cat_name.setGeometry(QtCore.QRect(140, 40, 230, 23))
        self.txt_sub_cat_name.setObjectName('txt_sub_cat_name')
        self.txt_url = QtWidgets.QLineEdit(Dialog)
        self.txt_url.setGeometry(QtCore.QRect(140, 70, 230, 23))
        self.txt_url.setObjectName('txt_url')
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate('Dialog', 'Add'))
        self.label_2.setText(_translate('Dialog', 'Sub Category Name :'))
        self.label.setText(_translate('Dialog', 'Category Name:'))
        self.btn_cancel.setText(_translate('Dialog', 'Cancel'))
        self.btn_save.setText(_translate('Dialog', 'Save'))
        self.label_3.setText(_translate('Dialog', 'URL :'))
        self.txt_cat_name.setPlaceholderText(_translate('Dialog', 'Category Name'))
        self.txt_sub_cat_name.setPlaceholderText(_translate('Dialog', 'Sub Category Name'))
        self.txt_url.setPlaceholderText(_translate('Dialog', 'URL'))