# # uncompyle6 version 3.8.1.dev0
# # Python bytecode 3.7.0 (3394)
# # Decompiled from: Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
# # Embedded file name: UiResults.py
# from PyQt5 import QtCore, QtGui, QtWidgets
#
# class Ui_MainWindow(object):
#
#     def setupUi(self, MainWindow):
#         MainWindow.setObjectName('MainWindow')
#         MainWindow.setWindowModality(QtCore.Qt.NonModal)
#         MainWindow.resize(823, 619)
#         icon = QtGui.QIcon()
#         icon.addPixmap(QtGui.QPixmap('res/09.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
#         MainWindow.setWindowIcon(icon)
#         self.centralwidget = QtWidgets.QWidget(MainWindow)
#         self.centralwidget.setObjectName('centralwidget')
#         self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
#         self.verticalLayout.setObjectName('verticalLayout')
#         self.verticalLayout_2 = QtWidgets.QVBoxLayout()
#         self.verticalLayout_2.setObjectName('verticalLayout_2')
#         self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
#         self.tableWidget.setMinimumSize(QtCore.QSize(799, 569))
#         self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
#         self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
#         self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
#         self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
#         self.tableWidget.setShowGrid(True)
#         self.tableWidget.setCornerButtonEnabled(True)
#         self.tableWidget.setObjectName('tableWidget')
#         self.tableWidget.setColumnCount(0)
#         self.tableWidget.setRowCount(0)
#         self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
#         self.tableWidget.horizontalHeader().setMinimumSectionSize(49)
#         self.tableWidget.verticalHeader().setDefaultSectionSize(37)
#         self.tableWidget.verticalHeader().setMinimumSectionSize(30)
#         self.verticalLayout_2.addWidget(self.tableWidget)
#         self.verticalLayout.addLayout(self.verticalLayout_2)
#         MainWindow.setCentralWidget(self.centralwidget)
#         self.menubar = QtWidgets.QMenuBar(MainWindow)
#         self.menubar.setGeometry(QtCore.QRect(0, 0, 823, 26))
#         self.menubar.setObjectName('menubar')
#         self.menuFile = QtWidgets.QMenu(self.menubar)
#         self.menuFile.setObjectName('menuFile')
#         MainWindow.setMenuBar(self.menubar)
#         self.actionCopy_to_Clipboard = QtWidgets.QAction(MainWindow)
#         self.actionCopy_to_Clipboard.setObjectName('actionCopy_to_Clipboard')
#         self.actionExport_to_Microsoft_Excel = QtWidgets.QAction(MainWindow)
#         self.actionExport_to_Microsoft_Excel.setObjectName('actionExport_to_Microsoft_Excel')
#         self.actionAdd_Prices = QtWidgets.QAction(MainWindow)
#         self.actionAdd_Prices.setObjectName('actionAdd_Prices')
#         self.menuFile.addAction(self.actionCopy_to_Clipboard)
#         self.menuFile.addAction(self.actionExport_to_Microsoft_Excel)
#         self.menuFile.addAction(self.actionAdd_Prices)
#         self.menubar.addAction(self.menuFile.menuAction())
#         self.retranslateUi(MainWindow)
#         QtCore.QMetaObject.connectSlotsByName(MainWindow)
#
#     def retranslateUi(self, MainWindow):
#         _translate = QtCore.QCoreApplication.translate
#         MainWindow.setWindowTitle(_translate('MainWindow', 'Results'))
#         self.tableWidget.setSortingEnabled(True)
#         self.menuFile.setTitle(_translate('MainWindow', 'File'))
#         self.actionCopy_to_Clipboard.setText(_translate('MainWindow', 'Copy to Clipboard'))
#         self.actionCopy_to_Clipboard.setShortcut(_translate('MainWindow', 'Ctrl+C'))
#         self.actionExport_to_Microsoft_Excel.setText(_translate('MainWindow', 'Export to Microsoft Excel'))
#         self.actionExport_to_Microsoft_Excel.setShortcut(_translate('MainWindow', 'Ctrl+E'))
#         self.actionAdd_Prices.setText(_translate('MainWindow', 'Add Prices'))


# uncompyle6 version 3.8.1.dev0
# Python bytecode 3.7.0 (3394)
# Decompiled from: Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)]
# Embedded file name: UiWebScraping.py
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName('MainWindow')
        MainWindow.resize(1032, 779)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('res/08.png'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName('centralwidget')
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName('horizontalLayout')
        self.TWCat = QtWidgets.QTreeWidget(self.centralwidget)
        self.TWCat.setIconSize(QtCore.QSize(32, 32))
        self.TWCat.setObjectName('TWCat')
        self.horizontalLayout.addWidget(self.TWCat)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 26))
        self.menubar.setObjectName('menubar')
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName('menuFile')
        # self.menuSites = QtWidgets.QMenu(self.menubar)
        # self.menuSites.setObjectName('menuSites')
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName('statusbar')
        MainWindow.setStatusBar(self.statusbar)
        # self.toolBar = QtWidgets.QToolBar(MainWindow)
        # self.toolBar.setIconSize(QtCore.QSize(32, 32))
        # self.toolBar.setObjectName('toolBar')
        # MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.act_Exit = QtWidgets.QAction(MainWindow)
        self.act_Exit.setObjectName('act_Exit')
        self.actionCopy_to_Clipboard = QtWidgets.QAction(MainWindow)
        self.actionCopy_to_Clipboard.setObjectName('actionCopy_to_Clipboard')
        self.actionExport_to_Microsoft_Excel = QtWidgets.QAction(MainWindow)
        self.actionExport_to_Microsoft_Excel.setObjectName('actionExport_to_Microsoft_Excel')
        self.menuFile.addAction(self.actionCopy_to_Clipboard)
        self.menuFile.addAction(self.actionExport_to_Microsoft_Excel)
        # self.URL_Souq = QtWidgets.QAction(MainWindow)
        # self.URL_Souq.setObjectName('URL_Souq')
        # self.URL_Carrefouregypt = QtWidgets.QAction(MainWindow)
        # self.URL_Carrefouregypt.setObjectName('URL_Carrefouregypt')
        # self.URL_2B = QtWidgets.QAction(MainWindow)
        # self.URL_2B.setObjectName('URL_2B')
        # self.URL_Cairosales = QtWidgets.QAction(MainWindow)
        # self.URL_Cairosales.setObjectName('URL_Cairosales')
        # self.URL_Btech = QtWidgets.QAction(MainWindow)
        # self.URL_Btech.setObjectName('URL_Btech')
        # self.URL_Jumia = QtWidgets.QAction(MainWindow)
        # self.URL_Jumia.setObjectName('URL_Jumia')
        # self.URL_Amazon = QtWidgets.QAction(MainWindow)
        # self.URL_Amazon.setObjectName('URL_Amazon')
        self.menuFile.addAction(self.act_Exit)
        # self.menuSites.addAction(self.URL_2B)
        # self.menuSites.addAction(self.URL_Cairosales)
        # self.menuSites.addAction(self.URL_Btech)
        # self.menuSites.addSeparator()
        # self.menuSites.addAction(self.URL_Carrefouregypt)
        # self.menuSites.addAction(self.URL_Jumia)
        # self.menuSites.addAction(self.URL_Amazon)
        self.menubar.addAction(self.menuFile.menuAction())
        # self.menubar.addAction(self.menuSites.menuAction())
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate('MainWindow', 'Web Scraping Beta'))
        # self.TWCat.headerItem().setText(0, _translate('MainWindow', 'Category'))
        # self.TWCat.headerItem().setText(1, _translate('MainWindow', 'URL'))
        self.menuFile.setTitle(_translate('MainWindow', 'File'))
        # self.menuSites.setTitle(_translate('MainWindow', 'Sites'))
        # self.toolBar.setWindowTitle(_translate('MainWindow', 'toolBar'))
        self.act_Exit.setText(_translate('MainWindow', 'Exit'))
        self.actionCopy_to_Clipboard.setText(_translate('MainWindow', 'Copy to Clipboard'))
        self.actionCopy_to_Clipboard.setShortcut(_translate('MainWindow', 'Ctrl+C'))
        self.actionExport_to_Microsoft_Excel.setText(_translate('MainWindow', 'Export to Microsoft Excel'))
        self.actionExport_to_Microsoft_Excel.setShortcut(_translate('MainWindow', 'Ctrl+E'))
        # self.URL_Souq.setText(_translate('MainWindow', 'Souq'))
        # self.URL_Carrefouregypt.setText(_translate('MainWindow', 'Carrefouregypt'))
        # self.URL_2B.setText(_translate('MainWindow', '2B'))
        # self.URL_Cairosales.setText(_translate('MainWindow', 'Cairosales'))
        # self.URL_Btech.setText(_translate('MainWindow', 'Btech'))
        # self.URL_Jumia.setText(_translate('MainWindow', 'Jumia'))
        # self.URL_Amazon.setText(_translate('MainWindow', 'Amazon'))